/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaz;

import Aplicacion.Producto;
import datos.dbsUnidad;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Percho
 */
public class Gestion_Unidad extends javax.swing.JInternalFrame {

    dbsUnidad logicaUnidad;
    /**
     * Creates new form Gestion_Unidad
     */
    public Gestion_Unidad() {
        initComponents();
        logicaUnidad=new dbsUnidad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbNuevoProducto = new javax.swing.JButton();
        jbBuscarProducto = new javax.swing.JButton();
        jtfCodigo = new javax.swing.JTextField();
        jbGuardarProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfTipo = new javax.swing.JComboBox();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestión de Unidades");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jtfValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfValorKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Tipo Unidad");

        jbNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cart_add.png"))); // NOI18N
        jbNuevoProducto.setText("Nuevo ");
        jbNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoProductoActionPerformed(evt);
            }
        });

        jbBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/magnifier.png"))); // NOI18N
        jbBuscarProducto.setText("Buscar ");

        jtfCodigo.setEditable(false);

        jbGuardarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cart_put.png"))); // NOI18N
        jbGuardarProducto.setText("Guardar ");
        jbGuardarProducto.setEnabled(false);
        jbGuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarProductoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Codigo Unidad");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nombre Unidad:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Valor Unidad");

        jtfTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UNIDAD", "PESO" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(52, 52, 52)
                                .addComponent(jtfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbGuardarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbNuevoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbNuevoProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbGuardarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbBuscarProducto)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorKeyTyped
        char car = evt.getKeyChar();
        //controlara que solo se ingresen caracteres numericos
        if ((car < '0' || car > '9') && car != (char) KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfValorKeyTyped

    private void jbNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoProductoActionPerformed
        limpiarComponentes();
        //asigna nuevo codigo al producto
        asignarCodigoProducto();

        jbGuardarProducto.setEnabled(true);
        jbNuevoProducto.setEnabled(false);

    }//GEN-LAST:event_jbNuevoProductoActionPerformed

    private void jbGuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarProductoActionPerformed
        if (guardarUnidad()) {
            if (regitrarUnidad()) {
                jbGuardarProducto.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Producto Registrado Correctamente");
                jbNuevoProducto.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jbGuardarProductoActionPerformed

       public void asignarCodigoProducto() {
        jtfCodigo.setText(new Producto().nuevoCodigo());
    }

    public void limpiarComponentes() {
        Object[] obj = new Object[]{jtfCodigo,jtfNombre, jtfValor};

        for (int i = 0; i < obj.length; i++) {
            if (obj[i] instanceof JTextField) {
                ((JTextField) obj[i]).setText("");
            } else if (obj[i] instanceof JTextArea) {
                ((JTextArea) obj[i]).setText("");
            }
        }
    }

    //este metodo me indica si puedo guardar el producto
    public boolean guardarUnidad() {
        if (camposVacios()) {
            JOptionPane.showMessageDialog(null, "Asegurese de ingresar todos los datos");
            return false;
        }
        return true;
    }

    //Este metodo me permite Registrar un Producto a la Vez
    public boolean regitrarUnidad() {
        try {
            Unidad uni=new Unidad();
            uni.setNombre(jtfNombre.getText().trim());
            uni.setValor(Double.parseDouble(jtfValor.getText().trim()));
            uni.setUnidad(jtfTipo.getSelectedItem().toString());
            logicaUnidad.insertar(uni);
        } catch (Exception ex) {
            System.out.println("ERROR"+ex.getMessage());
            //jtaMensajes.setText("Revise el formato del precio.... \n Causa:....\n" + ex.getCause());
        }
        return false;
    }

    public boolean camposVacios() {
        boolean bandera = false;
         Object[] obj = new Object[]{jtfNombre, jtfValor};

        for (int i = 0; i < obj.length; i++) {
            if (obj[i] instanceof JTextField) {
                ((JTextField) obj[i]).setBackground(Color.WHITE);
                if (((JTextField) obj[i]).getText().trim().equals("")) {
                    ((JTextField) obj[i]).setBackground(Color.GREEN);
                    bandera = true;
                }
            } else if (obj[i] instanceof JTextArea) {
                ((JTextArea) obj[i]).setBackground(Color.WHITE);
                if (((JTextArea) obj[i]).getText().trim().equals("")) {
                    ((JTextArea) obj[i]).setBackground(Color.GREEN);
                    bandera = true;
                }
            }
        }
        return bandera;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbBuscarProducto;
    private javax.swing.JButton jbGuardarProducto;
    private javax.swing.JButton jbNuevoProducto;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JComboBox jtfTipo;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
}
